"""Recent events and commentaries for context and dedupe. Holds the user's recipe for mentor mode."""
from typing import List


class RecentMemory:
    """Keep last N events and M commentaries for prompts and filtering. Can store the recipe the user is following."""

    def __init__(self, max_events: int = 10, max_commentaries: int = 5):
        self.max_events = max_events
        self.max_commentaries = max_commentaries
        self._events: List[str] = []
        self._commentaries: List[str] = []
        self._recipe: str = ""  # Dish name (e.g. "Pasta", "Scrambled eggs")
        self._recipe_steps: str = ""  # Full step-by-step recipe generated by AI for the session

    def set_recipe(self, recipe: str) -> None:
        """Set the dish name the user is making (e.g. 'Pasta', 'scrambled eggs')."""
        self._recipe = (recipe or "").strip()

    def get_recipe(self) -> str:
        """Dish name for mentor-style guidance."""
        return self._recipe

    def set_recipe_steps(self, steps: str) -> None:
        """Set the full recipe steps (AI-generated) for the session."""
        self._recipe_steps = (steps or "").strip()

    def get_recipe_steps(self) -> str:
        """Full recipe steps so the mentor can reference next step and guide."""
        return self._recipe_steps

    def add_events(self, events: List[str]) -> None:
        for e in events:
            self._events.append(e)
        if len(self._events) > self.max_events:
            self._events = self._events[-self.max_events :]

    def add_commentary(self, commentary: str) -> None:
        if commentary and commentary.strip():
            self._commentaries.append(commentary.strip())
        if len(self._commentaries) > self.max_commentaries:
            self._commentaries = self._commentaries[-self.max_commentaries :]

    def get_context(self) -> str:
        """Short context string for the prompt (recent commentaries)."""
        if not self._commentaries:
            return ""
        return " | ".join(self._commentaries[-3:])

    def get_recent_events_summary(self) -> str:
        """Recent cooking actions for the prompt so the mentor can track progress."""
        if not self._events:
            return ""
        return " | ".join(self._events[-5:])

    def get_recent_commentaries(self) -> List[str]:
        return list(self._commentaries)
